- [/imu/data, Imu, imu_data]
- [/imu/data_raw, Imu, imu_data_raw]
- [/heading, Float64, heading]
- [/roll, Float64, roll]
- [/pitch, Float64, pitch]
- [/cpu/temperature, Int8, cpu_temp]
- [/depth, Float64, depth]
- [/gps_odom, Odometry, gps_odom]
- [/dvl/odom, Odometry, dvl_odom]
